### ISSUE TITLE
How to present Dashboard

### ISSUE THREAD

**Issue by yilinxia** [arviz-devs/arviz_dashboard#6]
we need to consider how the dashboard will be shown. We currently have a dashboard embedded within a Jupyter lab (notebook). However, it is important to consider if the dashboard should be used as an extension to Jupyter or as a standalone website.

**Comment by ndmlny-qs** [comment]
My opinion about this is to choose one platform where we can successfully create a dashboard. As it stands, you have created a successful dashboard in Jupyter. When/If we need to add another platform (e.g. Colab) then we can think about how to achieve this. But for now my opinion is to focus on JupyterLab only, and not as an extension, but as inline interactive dashboards. Again, if we need/want to add the dashboards as Jupyter extensions, then we can, but that is a future decision.

**Comment by yilinxia** [comment]
Yeah, jupyter extension is a future direction. Right now, if the users install the package then they can call the function to generate a dashboard, which also applies to Colab.

**Comment by aloctavodia** [comment]
Agreed, we should first target inline interactive dashboards that run on Jupyter.
