### ISSUE TITLE
Change name of main branch

### ISSUE THREAD

**Issue by ndmlny-qs** [arviz-devs/arviz_dashboard#9]

**Comment by ndmlny-qs** [comment]
@aloctavodia and @yilinxia I'd like to change the main branch name to `main`. If there are no objections, then I'll make the change.

**Comment by yilinxia** [comment]
Thank you Andy for the suggestion! I dont mind at all :)

**Comment by aloctavodia** [comment]
Good idea!

**Comment by ndmlny-qs** [comment]
@aloctavodia you will need to change the current default branch to the newly created `main` branch. You can do so by following step 4 and 5 on this site

https://stevenmortimer.com/5-steps-to-change-github-default-branch-from-master-to-main/

I would do it, but I don't have those privileges. Thanks for the change.

**Comment by OriolAbril** [comment]
github has a rename branch feature, I can use that too if you don't mind

**Comment by ndmlny-qs** [comment]
sure, I didn't realize it had that feature. That's super

**Comment by OriolAbril** [comment]
Done, now I see this message:

![imatge](https://user-images.githubusercontent.com/23738400/206578194-28385413-f83b-49d0-b971-f3105164d067.png)

with commands:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

I assume you will see the same message but posting anyway just in case.

**Comment by ndmlny-qs** [comment]
Awesome, thanks again everyone.

Closing the issue, but it will still be around if anyone needs to reference it.
